from car import Car
car_1 = Car("ongthing","OTL",2012,"yello")
car_2 = Car("ford","mostag",2013,"red")
print(car_1.make)
print(car_1.model)
print(car_1.color)
print(car_1.year)
print(car_2.make)
print(car_2.model)
print(car_2.year)
print(car_2.color)
car_1.drive()
car_2.stop()